/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.sibies.Vistas;

import com.mycompany.sibies.DAO.Conexion;
import com.mycompany.sibies.DAO.Constantes;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jesus
 */
public class JfEstudiantes extends javax.swing.JFrame {

    /**
     * Creates new form JfEstudiantes
     */
    public JfEstudiantes() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public void filtrarEstudiantes (String buscar){
        
         String sql = null;
         
        Statement st; 
        Conexion con = new Conexion();
        Connection conexion = con.getConexion();
        System.out.println(sql);
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Nombres");
        model.addColumn("Apellidos");
        model.addColumn("Periodo");
        model.addColumn("Carrera");
        model.addColumn("Numero identificacion");
        model.addColumn("Telefono");
        model.addColumn("Correo");
        model.addColumn("Sexo");
        model.addColumn("Observacion");
        
        
        tableestudiantes.setModel(model);
        String [] datos = new String[9];
        
        if(buscar.equals("")){
            sql= "SELECT * FROM "+Constantes.T_ESTUDIANTES;
        }
        else{
            sql= "SELECT * FROM "+Constantes.T_ESTUDIANTES+ " WHERE "+Constantes.TE_DOCUMENTO+ " LIKE '%"+buscar+"%' OR " +Constantes.TE_NOMBRE+" LIKE '%"+buscar+"%' OR "+Constantes.TE_APELLIDO+" LIKE '%"+buscar+"%'";
        }
        
        try {
            st= (Statement) conexion.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()){
                datos[0] = rs.getString(1);
                datos[1] = rs.getString(2);
                datos[2] = rs.getString(3);
                datos[3] = rs.getString(4);
                datos[4] = rs.getString(5);
                datos[5] = rs.getString(6);
                datos[6] = rs.getString(7);
                datos[7] = rs.getString(8);
                datos[8] = rs.getString(9);
                
                
                model.addRow(datos);
            }
                    
        } catch (SQLException e) {
        }
        
        
    }
    
    public void mostrarEstudiantes(){
        String sql= "SELECT * FROM "+Constantes.T_ESTUDIANTES;
        Statement st; 
        Conexion con = new Conexion();
        Connection conexion = con.getConexion();
        System.out.println(sql);
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Nombres");
        model.addColumn("Apellidos");
        model.addColumn("Periodo");
        model.addColumn("Carrera");
        model.addColumn("Numero identificacion");
        model.addColumn("Telefono");
        model.addColumn("Correo");
        model.addColumn("Sexo");
        model.addColumn("Observacion");
        
        tableestudiantes.setModel(model);
        String [] datos = new String[9];
        
        try {
            st= (Statement) conexion.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()){
                datos[0] = rs.getString(1);
                datos[1] = rs.getString(2);
                datos[2] = rs.getString(3);
                datos[3] = rs.getString(4);
                datos[4] = rs.getString(5);
                datos[5] = rs.getString(6);
                datos[6] = rs.getString(7);
                datos[7] = rs.getString(8);
                datos[8] = rs.getString(9);
                
                model.addRow(datos);
            }
                    
        } catch (SQLException e) {
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btVolverEstudiantes = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        BtBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableestudiantes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Estudiantes"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btVolverEstudiantes.setText("Volver");
        btVolverEstudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVolverEstudiantesActionPerformed(evt);
            }
        });
        jPanel1.add(btVolverEstudiantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 110, -1, -1));

        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 379, -1));

        BtBuscar.setText("Buscar");
        BtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(BtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 170, -1, -1));

        tableestudiantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tableestudiantes);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 690, 340));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Trina\\Downloads\\Panel sibies.jpg")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btVolverEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVolverEstudiantesActionPerformed
        JfpanelControl jfpanel = new JfpanelControl();
        jfpanel.setVisible(true);
              this.dispose();
    }//GEN-LAST:event_btVolverEstudiantesActionPerformed

    private void BtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtBuscarActionPerformed
        // BOTON DE BUSCAR ESTUDIANTE

        if (txtBuscar.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor ingrese un dato para realizar la busqueda");
        } else {
            filtrarEstudiantes(txtBuscar.getText());
        }

    }//GEN-LAST:event_BtBuscarActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JfEstudiantes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BtBuscar;
    public javax.swing.JButton btVolverEstudiantes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tableestudiantes;
    public javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
