/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.sibies.Vistas;

import com.mycompany.sibies.DAO.Conexion;
import com.mycompany.sibies.DAO.Constantes;
import com.mycompany.sibies.DAO.DaoEstudiantes;
import com.mycompany.sibies.Modelos.Estudiantes;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author Jesus
 */
public class Jfmatriculado extends javax.swing.JFrame {

    /**
     * Creates new form Jfmatriculado
     */
    public Jfmatriculado() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public void mostrar(){
        String sql= "SELECT * FROM "+Constantes.T_ESTUDIANTES;
        Statement st; 
        Conexion con = new Conexion();
        Connection conexion = con.getConexion();
        System.out.println(sql); 
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Nombres");
        model.addColumn("Apellidos");
        model.addColumn("Periodo");
        model.addColumn("Carrera");
        model.addColumn("Numero identificacion");
        model.addColumn("Telefono");
        model.addColumn("Correo");
        model.addColumn("Sexo");
        model.addColumn("Observacion");
        
        tablavermatriculados.setModel(model);
        String [] datos = new String[9];
        
        try {
            st= (Statement) conexion.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()){
                datos[0] = rs.getString(1);
                datos[1] = rs.getString(2);
                datos[2] = rs.getString(3);
                datos[3] = rs.getString(4);
                datos[4] = rs.getString(5);
                datos[5] = rs.getString(6);
                datos[6] = rs.getString(7);
                datos[7] = rs.getString(8);
                datos[8] = rs.getString(9);
                
                model.addRow(datos);
            }
                    
        } catch (SQLException e) {
        }
        
            
        
    }
    
    public void modificarEstudiante(){
        int fila = tablavermatriculados.getSelectedRow();
        if(fila>=0){
            txtnombres.setText(tablavermatriculados.getValueAt(fila, 0).toString());
            txtapellidos.setText(tablavermatriculados.getValueAt(fila, 1).toString());
            txtperiodo.setText(tablavermatriculados.getValueAt(fila, 2).toString());
            txtcarrera.setText(tablavermatriculados.getValueAt(fila, 3).toString());
            txtnumeroidentificacion.setText(tablavermatriculados.getValueAt(fila, 4).toString());
            txttelefono.setText(tablavermatriculados.getValueAt(fila, 5).toString());
            txtcorreo.setText(tablavermatriculados.getValueAt(fila, 6).toString());
            txtsexo.setText(tablavermatriculados.getValueAt(fila, 7).toString());
            txtobservacion.setText(tablavermatriculados.getValueAt(fila, 8).toString());
            
            
        } else{
            JOptionPane.showMessageDialog(null, "Seleccione fila");
        }
        
    }
    
    
    
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LabelNombre = new javax.swing.JLabel();
        LabelCorreo = new javax.swing.JLabel();
        LabelApellido = new javax.swing.JLabel();
        LabelObservacion = new javax.swing.JLabel();
        LabelSexo = new javax.swing.JLabel();
        LabelNumeroIdenti = new javax.swing.JLabel();
        LabelCarrera = new javax.swing.JLabel();
        LabelTelefono = new javax.swing.JLabel();
        LabelPeriodo = new javax.swing.JLabel();
        txtnombres = new javax.swing.JTextField();
        txttelefono = new javax.swing.JTextField();
        txtapellidos = new javax.swing.JTextField();
        txtcarrera = new javax.swing.JTextField();
        txtperiodo = new javax.swing.JTextField();
        txtnumeroidentificacion = new javax.swing.JTextField();
        txtsexo = new javax.swing.JTextField();
        txtcorreo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtobservacion = new javax.swing.JTextArea();
        BtregistrarEstudiantes = new javax.swing.JButton();
        Btrefrecar = new javax.swing.JButton();
        BtVolverMatriPanel = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablavermatriculados = new javax.swing.JTable();
        btmodificar = new javax.swing.JButton();
        imagenfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelNombre.setText("Nombres: ");
        jPanel1.add(LabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        LabelCorreo.setText("Correo Electronico:");
        jPanel1.add(LabelCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 530, 110, -1));

        LabelApellido.setText("Apellidos:");
        jPanel1.add(LabelApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        LabelObservacion.setText("Observacion:");
        jPanel1.add(LabelObservacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, -1, -1));

        LabelSexo.setText("Sexo:");
        jPanel1.add(LabelSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, -1, -1));

        LabelNumeroIdenti.setText("Numero de identificacion: ");
        jPanel1.add(LabelNumeroIdenti, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, 150, -1));

        LabelCarrera.setText("Programa Academico:");
        jPanel1.add(LabelCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, -1, -1));

        LabelTelefono.setText("Telefono:");
        jPanel1.add(LabelTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 590, -1, 20));

        LabelPeriodo.setText("Periodo Matriculado:");
        jPanel1.add(LabelPeriodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, -1, -1));
        jPanel1.add(txtnombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 174, -1));
        jPanel1.add(txttelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 610, 174, -1));
        jPanel1.add(txtapellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 174, -1));
        jPanel1.add(txtcarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 174, -1));
        jPanel1.add(txtperiodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 174, -1));
        jPanel1.add(txtnumeroidentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 174, -1));
        jPanel1.add(txtsexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 490, 174, -1));
        jPanel1.add(txtcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 550, 174, -1));

        txtobservacion.setColumns(20);
        txtobservacion.setRows(5);
        jScrollPane1.setViewportView(txtobservacion);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, -1, 124));

        BtregistrarEstudiantes.setText("REGISTRAR");
        BtregistrarEstudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtregistrarEstudiantesActionPerformed(evt);
            }
        });
        jPanel1.add(BtregistrarEstudiantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, 100, 30));

        Btrefrecar.setText("REFRESCAR");
        Btrefrecar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtrefrecarActionPerformed(evt);
            }
        });
        jPanel1.add(Btrefrecar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 460, -1, -1));

        BtVolverMatriPanel.setText("Volver");
        BtVolverMatriPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtVolverMatriPanelActionPerformed(evt);
            }
        });
        jPanel1.add(BtVolverMatriPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 110, -1, -1));

        tablavermatriculados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablavermatriculados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablavermatriculadosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablavermatriculados);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, 625, 250));

        btmodificar.setText("MODIFICAR");
        btmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmodificarActionPerformed(evt);
            }
        });
        jPanel1.add(btmodificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, -1, 30));

        imagenfondo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Trina\\Downloads\\PANEL NUEVO_page-0001 (2).jpg")); // NOI18N
        imagenfondo.setText("jLabel1");
        jPanel1.add(imagenfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1306, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtregistrarEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtregistrarEstudiantesActionPerformed
        // BOTON PARA REGISTRAR ESTUDIANTES

        DaoEstudiantes daoEstudiantes = new DaoEstudiantes();
        Estudiantes estudiantes = new Estudiantes();

        if (txtnombres.getText().equals("") || txtapellidos.getText().equals("") || txtperiodo.getText().equals("") || txtcarrera.getText().equals("") || txtnumeroidentificacion.getText().equals("") || txttelefono.getText().equals("") || txtcorreo.getText().equals("") || txtsexo.getText().equals("")) {

            JOptionPane.showMessageDialog(null, "Campos vacios, debe llenar todos los campos");
        } else {

            if (daoEstudiantes.esEmail(txtcorreo.getText())) {

                estudiantes.setNombres(txtnombres.getText());
                estudiantes.setApellidos(txtapellidos.getText());
                estudiantes.setPeriodoMatricula(txtperiodo.getText());
                estudiantes.setCarrera(txtcarrera.getText());
                estudiantes.setNumeroIdentificacion(txtnumeroidentificacion.getText());
                estudiantes.setTelefono(txttelefono.getText());
                estudiantes.setCorreo(txtcorreo.getText());
                estudiantes.setObservacion(txtobservacion.getText());
                estudiantes.setSexo(txtsexo.getText());

                if (daoEstudiantes.registrar(estudiantes)) {
                    JOptionPane.showMessageDialog(null, "Registro Guardado");
                    limpiar();
                    mostrar();
                } else {
                    JOptionPane.showMessageDialog(null, "Error al guardar");

                }
            } else {
                JOptionPane.showMessageDialog(null, "El correo electronico no es valido, use el formato institucional");
                limpiarCorreo();

            }

        }
    }//GEN-LAST:event_BtregistrarEstudiantesActionPerformed

    private void BtVolverMatriPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtVolverMatriPanelActionPerformed
        // BOTON DE VOLVER DE MATRICULADO A PANEL DE CONTROL 
        JfpanelControl Jfpanel = new JfpanelControl();
        Jfpanel.setVisible(true);
              this.dispose();
    }//GEN-LAST:event_BtVolverMatriPanelActionPerformed

    private void btmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmodificarActionPerformed
        // MODIFICAR DATOS
        DaoEstudiantes daoEstudiantes = new DaoEstudiantes();
        Estudiantes estudiantes = new Estudiantes();

        estudiantes.setNombres(txtnombres.getText());
        estudiantes.setApellidos(txtapellidos.getText());
        estudiantes.setPeriodoMatricula(txtperiodo.getText());
        estudiantes.setCarrera(txtcarrera.getText());
        estudiantes.setNumeroIdentificacion(txtnumeroidentificacion.getText());
        estudiantes.setTelefono(txttelefono.getText());
        estudiantes.setCorreo(txtcorreo.getText());
        estudiantes.setObservacion(txtobservacion.getText());
        estudiantes.setSexo(txtsexo.getText());
        
        daoEstudiantes.modificarDatos(estudiantes);
    }//GEN-LAST:event_btmodificarActionPerformed

    private void tablavermatriculadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablavermatriculadosMouseClicked
        modificarEstudiante();
    }//GEN-LAST:event_tablavermatriculadosMouseClicked

    private void BtrefrecarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtrefrecarActionPerformed
        // TODO add your handling code here:
        mostrar();
        
    }//GEN-LAST:event_BtrefrecarActionPerformed

    private void limpiar (){
        txtnombres.setText("");
        txtapellidos.setText("");
        txtperiodo.setText("");
        txtcarrera.setText("");
        txtnumeroidentificacion.setText("");
        txttelefono.setText("");
        txtcorreo.setText("");
        txtobservacion.setText("");
        txtsexo.setText(""); 
    }
    private void limpiarCorreo (){
        txtcorreo.setText("");
    }
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jfmatriculado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jfmatriculado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jfmatriculado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jfmatriculado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jfmatriculado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BtVolverMatriPanel;
    private javax.swing.JButton Btrefrecar;
    private javax.swing.JButton BtregistrarEstudiantes;
    private javax.swing.JLabel LabelApellido;
    private javax.swing.JLabel LabelCarrera;
    private javax.swing.JLabel LabelCorreo;
    private javax.swing.JLabel LabelNombre;
    private javax.swing.JLabel LabelNumeroIdenti;
    private javax.swing.JLabel LabelObservacion;
    private javax.swing.JLabel LabelPeriodo;
    private javax.swing.JLabel LabelSexo;
    private javax.swing.JLabel LabelTelefono;
    private javax.swing.JButton btmodificar;
    private javax.swing.JLabel imagenfondo;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable tablavermatriculados;
    public javax.swing.JTextField txtapellidos;
    public javax.swing.JTextField txtcarrera;
    public javax.swing.JTextField txtcorreo;
    public javax.swing.JTextField txtnombres;
    public javax.swing.JTextField txtnumeroidentificacion;
    public javax.swing.JTextArea txtobservacion;
    public javax.swing.JTextField txtperiodo;
    public javax.swing.JTextField txtsexo;
    public javax.swing.JTextField txttelefono;
    // End of variables declaration//GEN-END:variables
}
