package com.mycompany.sibies.Vistas;

public class JfpanelControl extends javax.swing.JFrame {

    public JfpanelControl() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Btcerrarsesion = new javax.swing.JButton();
        Btmatriculado = new javax.swing.JButton();
        Btestudiante = new javax.swing.JButton();
        imagenPanel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Btcerrarsesion.setText("Cerrar Sesión ");
        Btcerrarsesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtcerrarsesionActionPerformed(evt);
            }
        });
        jPanel1.add(Btcerrarsesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 120, 120, 30));

        Btmatriculado.setText("MATRICULADO");
        Btmatriculado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtmatriculadoActionPerformed(evt);
            }
        });
        jPanel1.add(Btmatriculado, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 210, 130, 70));

        Btestudiante.setText("ESTUDIANTE");
        Btestudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtestudianteActionPerformed(evt);
            }
        });
        jPanel1.add(Btestudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, 130, 70));

        imagenPanel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Trina\\Downloads\\Panel sibies.jpg")); // NOI18N
        jPanel1.add(imagenPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtcerrarsesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtcerrarsesionActionPerformed
        // BOTON PARA CERRAR SESION DE PANEL DE CONTROL A LOGIN 
        Jflogin jflogin = new Jflogin();
        jflogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtcerrarsesionActionPerformed

    private void BtmatriculadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtmatriculadoActionPerformed
        // BOTON PARA ENTRAR A LA VISTA MATRICULADO 
        Jfmatriculado jfmatriculado = new Jfmatriculado();
        jfmatriculado.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtmatriculadoActionPerformed

    private void BtestudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtestudianteActionPerformed
        JfEstudiantes jfEstudiantes = new JfEstudiantes();
        jfEstudiantes.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtestudianteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfpanelControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfpanelControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfpanelControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfpanelControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JfpanelControl().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Btcerrarsesion;
    public javax.swing.JButton Btestudiante;
    public javax.swing.JButton Btmatriculado;
    private javax.swing.JLabel imagenPanel;
    public javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
